"""Initial migration

Revision ID: 6fc7a98f4fea
Revises: 
Create Date: 2025-07-25 17:04:28.707383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc7a98f4fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('amenities',
    # sa.Column('name', sa.String(length=50), nullable=False),
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('users',
    # sa.Column('email', sa.String(length=120), nullable=False),
    # sa.Column('first_name', sa.String(length=60), nullable=False),
    # sa.Column('last_name', sa.String(length=60), nullable=False),
    # sa.Column('password', sa.String(length=128), nullable=False),
    # sa.Column('is_admin', sa.Boolean(), nullable=True),
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    # op.create_table('places',
    # sa.Column('owner_id', sa.String(length=36), nullable=False),
    # sa.Column('title', sa.String(length=128), nullable=False),
    # sa.Column('description', sa.String(length=1024), nullable=True),
    # sa.Column('price', sa.Float(), nullable=False),
    # sa.Column('latitude', sa.Float(), nullable=True),
    # sa.Column('longitude', sa.Float(), nullable=True),
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('place_amenity',
    # sa.Column('place_id', sa.String(length=36), nullable=False),
    # sa.Column('amenity_id', sa.String(length=36), nullable=False),
    # sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    # sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    # sa.PrimaryKeyConstraint('place_id', 'amenity_id')
    # )
    # op.create_table('reviews',
    # sa.Column('text', sa.Text(), nullable=False),
    # sa.Column('rating', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.String(length=36), nullable=False),
    # sa.Column('place_id', sa.String(length=36), nullable=False),
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('user_id', 'place_id', name='uq_user_place_review')
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('place_amenity')
    op.drop_table('places')
    op.drop_table('users')
    op.drop_table('amenities')
    # ### end Alembic commands ###
